### ISSUE TITLE
all errors

### ISSUE THREAD

**Issue by ardadasdelen** [itsqezy/Proxyless-Spotify-Follow-Bot#2]
Hello, you need to help me, can I get a bot installation video or can you explain the installation steps one by one?

**Comment by skiddedlarps** [comment]
Hey, This is 100% working it is not patched, If you have discord please contact me there (Qezy#1337). I can help you from there, If you although dont have discord ---> Heres what to do

- Run it, open a different browser or something you use to https://open.spotify.com then, check followers

Yours Truly,
Qezy#1337

**Comment by ardadasdelen** [comment]
> Hey, Bu %100 çalışıyor, yamalı değil, Uyuşmazlığınız varsa lütfen benimle oradan iletişime geçin (Qezy#1337). Oradan size yardımcı olabilirim, eğer anlaşmazlığınız yoksa ---> Yapmanız gerekenler
> 
> * [Çalıştırın, farklı bir tarayıcı açın veya https://open.spotify.com](https://open.spotify.com) için kullandığınız bir şey açın, ardından takipçileri kontrol edin
> 
> Saygılarımla, Qezy#1337

First of all, I'm going to try what you said right away and I want to tell you that I sent you a request on discord, please accept me الله#6627 Take it easy Thanks Bye

**Comment by ardadasdelen** [comment]
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering
Error [RATELIMIT] while registering

I am encountering this error

**Comment by ardadasdelen** [comment]
Spotify account is created but not followed
